// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartButton_linx from "./islands/AddToCartButton/linx.tsx";
import * as $AddToCartButton_nuvemshop from "./islands/AddToCartButton/nuvemshop.tsx";
import * as $AddToCartButton_shopify from "./islands/AddToCartButton/shopify.tsx";
import * as $AddToCartButton_vnda from "./islands/AddToCartButton/vnda.tsx";
import * as $AddToCartButton_vtex from "./islands/AddToCartButton/vtex.tsx";
import * as $AddToCartButton_wake from "./islands/AddToCartButton/wake.tsx";
import * as $BrowserLog from "./islands/BrowserLog.tsx";
import * as $CopyButton from "./islands/CopyButton.tsx";
import * as $Iframe from "./islands/Iframe.tsx";
import * as $LayoutSwitcherScript from "./islands/LayoutSwitcherScript.ts";
import * as $Logger from "./islands/Logger.tsx";
import * as $MicroHeaderSetup from "./islands/MicroHeaderSetup.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $OutOfStock_vtex from "./islands/OutOfStock/vtex.tsx";
import * as $OutOfStock_wake from "./islands/OutOfStock/wake.tsx";
import * as $ProductBuyTogether from "./islands/ProductBuyTogether.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $ProductReviews_vtex from "./islands/ProductReviews/vtex.tsx";
import * as $ProductReviews_wake from "./islands/ProductReviews/wake.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $ShippingSimulator_Vtex from "./islands/ShippingSimulator/Vtex.tsx";
import * as $ShippingSimulator_Wake from "./islands/ShippingSimulator/Wake.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $ThirdPartyScripts from "./islands/ThirdPartyScripts.tsx";
import * as $ThirdPartyScriptsNoDelay from "./islands/ThirdPartyScriptsNoDelay.tsx";
import * as $TriggerElement from "./islands/TriggerElement.tsx";
import * as $WishlistButton_vtex from "./islands/WishlistButton/vtex.tsx";
import * as $WishlistButton_wake from "./islands/WishlistButton/wake.tsx";
import * as $ZoomableImage from "./islands/ZoomableImage.tsx";
import * as $filters_PriceRange from "./islands/filters/PriceRange.tsx";
import * as $filters_mobile_Buttons from "./islands/filters/mobile/Buttons.tsx";
import * as $forms_contact_Vtex from "./islands/forms/contact/Vtex.tsx";
import * as $forms_contact_Wake from "./islands/forms/contact/Wake.tsx";
import * as $header_Buttons from "./islands/header/Buttons.tsx";
import * as $header_Cart_linx from "./islands/header/Cart/linx.tsx";
import * as $header_Cart_nuvemshop from "./islands/header/Cart/nuvemshop.tsx";
import * as $header_Cart_shopify from "./islands/header/Cart/shopify.tsx";
import * as $header_Cart_vnda from "./islands/header/Cart/vnda.tsx";
import * as $header_Cart_vtex from "./islands/header/Cart/vtex.tsx";
import * as $header_Cart_wake from "./islands/header/Cart/wake.tsx";
import * as $header_Drawers from "./islands/header/Drawers.tsx";
import * as $header_FreeShippingProgressBar_linx from "./islands/header/FreeShippingProgressBar/linx.tsx";
import * as $header_FreeShippingProgressBar_nuvemshop from "./islands/header/FreeShippingProgressBar/nuvemshop.tsx";
import * as $header_FreeShippingProgressBar_shopify from "./islands/header/FreeShippingProgressBar/shopify.tsx";
import * as $header_FreeShippingProgressBar_vnda from "./islands/header/FreeShippingProgressBar/vnda.tsx";
import * as $header_FreeShippingProgressBar_vtex from "./islands/header/FreeShippingProgressBar/vtex.tsx";
import * as $header_FreeShippingProgressBar_wake from "./islands/header/FreeShippingProgressBar/wake.tsx";
import * as $header_Login_vtex from "./islands/header/Login/vtex.tsx";
import * as $header_Login_wake from "./islands/header/Login/wake.tsx";
import * as $header_Searchbar from "./islands/header/Searchbar.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartButton/linx.tsx": $AddToCartButton_linx,
    "./islands/AddToCartButton/nuvemshop.tsx": $AddToCartButton_nuvemshop,
    "./islands/AddToCartButton/shopify.tsx": $AddToCartButton_shopify,
    "./islands/AddToCartButton/vnda.tsx": $AddToCartButton_vnda,
    "./islands/AddToCartButton/vtex.tsx": $AddToCartButton_vtex,
    "./islands/AddToCartButton/wake.tsx": $AddToCartButton_wake,
    "./islands/BrowserLog.tsx": $BrowserLog,
    "./islands/CopyButton.tsx": $CopyButton,
    "./islands/Iframe.tsx": $Iframe,
    "./islands/LayoutSwitcherScript.ts": $LayoutSwitcherScript,
    "./islands/Logger.tsx": $Logger,
    "./islands/MicroHeaderSetup.tsx": $MicroHeaderSetup,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/OutOfStock/vtex.tsx": $OutOfStock_vtex,
    "./islands/OutOfStock/wake.tsx": $OutOfStock_wake,
    "./islands/ProductBuyTogether.tsx": $ProductBuyTogether,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/ProductReviews/vtex.tsx": $ProductReviews_vtex,
    "./islands/ProductReviews/wake.tsx": $ProductReviews_wake,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/ShippingSimulator/Vtex.tsx": $ShippingSimulator_Vtex,
    "./islands/ShippingSimulator/Wake.tsx": $ShippingSimulator_Wake,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/ThirdPartyScripts.tsx": $ThirdPartyScripts,
    "./islands/ThirdPartyScriptsNoDelay.tsx": $ThirdPartyScriptsNoDelay,
    "./islands/TriggerElement.tsx": $TriggerElement,
    "./islands/WishlistButton/vtex.tsx": $WishlistButton_vtex,
    "./islands/WishlistButton/wake.tsx": $WishlistButton_wake,
    "./islands/ZoomableImage.tsx": $ZoomableImage,
    "./islands/filters/PriceRange.tsx": $filters_PriceRange,
    "./islands/filters/mobile/Buttons.tsx": $filters_mobile_Buttons,
    "./islands/forms/contact/Vtex.tsx": $forms_contact_Vtex,
    "./islands/forms/contact/Wake.tsx": $forms_contact_Wake,
    "./islands/header/Buttons.tsx": $header_Buttons,
    "./islands/header/Cart/linx.tsx": $header_Cart_linx,
    "./islands/header/Cart/nuvemshop.tsx": $header_Cart_nuvemshop,
    "./islands/header/Cart/shopify.tsx": $header_Cart_shopify,
    "./islands/header/Cart/vnda.tsx": $header_Cart_vnda,
    "./islands/header/Cart/vtex.tsx": $header_Cart_vtex,
    "./islands/header/Cart/wake.tsx": $header_Cart_wake,
    "./islands/header/Drawers.tsx": $header_Drawers,
    "./islands/header/FreeShippingProgressBar/linx.tsx":
      $header_FreeShippingProgressBar_linx,
    "./islands/header/FreeShippingProgressBar/nuvemshop.tsx":
      $header_FreeShippingProgressBar_nuvemshop,
    "./islands/header/FreeShippingProgressBar/shopify.tsx":
      $header_FreeShippingProgressBar_shopify,
    "./islands/header/FreeShippingProgressBar/vnda.tsx":
      $header_FreeShippingProgressBar_vnda,
    "./islands/header/FreeShippingProgressBar/vtex.tsx":
      $header_FreeShippingProgressBar_vtex,
    "./islands/header/FreeShippingProgressBar/wake.tsx":
      $header_FreeShippingProgressBar_wake,
    "./islands/header/Login/vtex.tsx": $header_Login_vtex,
    "./islands/header/Login/wake.tsx": $header_Login_wake,
    "./islands/header/Searchbar.tsx": $header_Searchbar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
