// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/createReview.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/records.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/wake.ts";
import * as $$$$$$$$$$$2 from "./apps/decohub.ts";
import * as $$$$$$$$$$$3 from "./apps/site.ts";
import * as $$$0 from "./loaders/List/Sections.tsx";
import * as $$$2 from "./loaders/reviews/hasShopperReviewedProduct.ts";
import * as $$$3 from "./loaders/reviews/productAverageRating.ts";
import * as $$$4 from "./loaders/reviews/productReviews.ts";
import * as $$$5 from "./loaders/reviews/productReviewsAndRatings.ts";
import * as $$$1 from "./loaders/Seals/seals.tsx";
import * as $$$6 from "./loaders/wakeBuyTogether.ts";
import * as $$$7 from "./loaders/wishlist/customVtexWishlist.ts";
import * as $$$8 from "./loaders/wishlist/customWakeWishlist.ts";
import * as $$$$$$$0 from "./matchers/canonical.ts";
import * as $$$$$$$1 from "./matchers/multipleCanonical.ts";
import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$1 from "./sections/Category/BreadcrumbPLP.tsx";
import * as $$$$$$2 from "./sections/Category/SeoText.tsx";
import * as $$$$$$3 from "./sections/Content/Benefits.tsx";
import * as $$$$$$4 from "./sections/Content/Hero.tsx";
import * as $$$$$$5 from "./sections/Content/RichText.tsx";
import * as $$$$$$6 from "./sections/Footer/Footer.tsx";
import * as $$$$$$7 from "./sections/Forms/Contact.tsx";
import * as $$$$$$8 from "./sections/Header/Header.tsx";
import * as $$$$$$9 from "./sections/Iframe.tsx";
import * as $$$$$$10 from "./sections/Images/BannerArray.tsx";
import * as $$$$$$11 from "./sections/Images/Carousel.tsx";
import * as $$$$$$12 from "./sections/Images/FullBanner.tsx";
import * as $$$$$$13 from "./sections/Institutional/Institutional.tsx";
import * as $$$$$$14 from "./sections/Institutional/InstitutionalBody.tsx";
import * as $$$$$$15 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$16 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$17 from "./sections/Product/BuyFloating.tsx";
import * as $$$$$$18 from "./sections/Product/NotFound.tsx";
import * as $$$$$$19 from "./sections/Product/Product.tsx";
import * as $$$$$$20 from "./sections/Product/ProductBuyTogether.tsx";
import * as $$$$$$21 from "./sections/Product/ProductDescription.tsx";
import * as $$$$$$22 from "./sections/Product/ProductReviews.tsx";
import * as $$$$$$23 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$24 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$25 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$26 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$27 from "./sections/SEO/PageSEO.tsx";
import * as $$$$$$28 from "./sections/Theme/Theme.tsx";
import * as $$$$$$29 from "./sections/Tools/ThirdPartyScripts.tsx";
import * as $$$$$$30 from "./sections/Tools/ThirdPartyScriptsNoDelay.tsx";

const manifest = {
  "loaders": {
    "site/loaders/List/Sections.tsx": $$$0,
    "site/loaders/reviews/hasShopperReviewedProduct.ts": $$$2,
    "site/loaders/reviews/productAverageRating.ts": $$$3,
    "site/loaders/reviews/productReviews.ts": $$$4,
    "site/loaders/reviews/productReviewsAndRatings.ts": $$$5,
    "site/loaders/Seals/seals.tsx": $$$1,
    "site/loaders/wakeBuyTogether.ts": $$$6,
    "site/loaders/wishlist/customVtexWishlist.ts": $$$7,
    "site/loaders/wishlist/customWakeWishlist.ts": $$$8,
  },
  "sections": {
    "site/sections/Animation/Animation.tsx": $$$$$$0,
    "site/sections/Category/BreadcrumbPLP.tsx": $$$$$$1,
    "site/sections/Category/SeoText.tsx": $$$$$$2,
    "site/sections/Content/Benefits.tsx": $$$$$$3,
    "site/sections/Content/Hero.tsx": $$$$$$4,
    "site/sections/Content/RichText.tsx": $$$$$$5,
    "site/sections/Footer/Footer.tsx": $$$$$$6,
    "site/sections/Forms/Contact.tsx": $$$$$$7,
    "site/sections/Header/Header.tsx": $$$$$$8,
    "site/sections/Iframe.tsx": $$$$$$9,
    "site/sections/Images/BannerArray.tsx": $$$$$$10,
    "site/sections/Images/Carousel.tsx": $$$$$$11,
    "site/sections/Images/FullBanner.tsx": $$$$$$12,
    "site/sections/Institutional/Institutional.tsx": $$$$$$13,
    "site/sections/Institutional/InstitutionalBody.tsx": $$$$$$14,
    "site/sections/Miscellaneous/CookieConsent.tsx": $$$$$$15,
    "site/sections/Newsletter/Newsletter.tsx": $$$$$$16,
    "site/sections/Product/BuyFloating.tsx": $$$$$$17,
    "site/sections/Product/NotFound.tsx": $$$$$$18,
    "site/sections/Product/Product.tsx": $$$$$$19,
    "site/sections/Product/ProductBuyTogether.tsx": $$$$$$20,
    "site/sections/Product/ProductDescription.tsx": $$$$$$21,
    "site/sections/Product/ProductReviews.tsx": $$$$$$22,
    "site/sections/Product/ProductShelf.tsx": $$$$$$23,
    "site/sections/Product/ProductShelfTabbed.tsx": $$$$$$24,
    "site/sections/Product/SearchResult.tsx": $$$$$$25,
    "site/sections/Product/Wishlist.tsx": $$$$$$26,
    "site/sections/SEO/PageSEO.tsx": $$$$$$27,
    "site/sections/Theme/Theme.tsx": $$$$$$28,
    "site/sections/Tools/ThirdPartyScripts.tsx": $$$$$$29,
    "site/sections/Tools/ThirdPartyScriptsNoDelay.tsx": $$$$$$30,
  },
  "matchers": {
    "site/matchers/canonical.ts": $$$$$$$0,
    "site/matchers/multipleCanonical.ts": $$$$$$$1,
  },
  "actions": {
    "site/actions/createReview.ts": $$$$$$$$$0,
  },
  "apps": {
    "site/apps/deco/records.ts": $$$$$$$$$$$0,
    "site/apps/deco/wake.ts": $$$$$$$$$$$1,
    "site/apps/decohub.ts": $$$$$$$$$$$2,
    "site/apps/site.ts": $$$$$$$$$$$3,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
